default: clean build
clean: 
	-rm variables datatypes pointers arrays
build:
	gcc -Wall variables.c -o variables
	gcc -Wall datatypes.c -o datatypes
	gcc -Wall pointers.c -o pointers
	gcc -Wall arrays.c -o arrays