all: struct1 struct2 struct3 struct4

struct1:
	gcc -Wall -o struct1 struct1.c

struct2:
	gcc -Wall -o struct2 struct2.c

struct3:
	gcc -Wall -o struct3 struct3.c

struct4:
	gcc -Wall -o struct4 struct4.c

clean:
	-rm struct1 struct2 struct3 struct4